colours_dict = {
    "teal": "#8dd3c7",
    "yellow": "#ffffb3",
    "purple": "#bebada",
    "red": "#fb8072",
    "blue": "#80b1d3",
    "lblue": "#a6cee3",
    "orange": "#fdb462",
    "green": "#b3de69",
    "lgreen": "#b2df8a",
    "pink": "#fccde5",
    "gray": "#d9d9d9",
    "violet": "#bc80bd",
    "mint": "#ccebc5",
    "gold": "#ffed6f",
    "gold1": "#fff6b3",
    "gold2": "#ffed6f",
    "gold3": "#ffe41a",
}
